name: Copyright year updater.

on: workflow_dispatch
jobs:
  Copyright-year:
    runs-on: ubuntu-slim
    steps:
      - uses: desktop-app/action_code_updater@master
        with:
          type: "license-year"
